routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\AdminAuthController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('cms.admin.parent');
})->middleware('auth:user');

Route::prefix('/cms/admin/')->middleware('auth:user')->group(function () {

    Route::resource('user', UserController::class);
    Route::resource('file', FileController::class);
    Route::get('logout', [AdminAuthController::class, 'logout'])->name('admin.logout');

    Route::get('password/reset', [AdminAuthController::class, 'showResetPasswordView'])->name('admin.password_reset_view');
    Route::post('password/reset', [AdminAuthController::class, 'resetPassword'])->name('admin.password_reset');

    Route::get('/', [AdminController::class, 'dashbord'])->name('admin.dashbord');
    Route::get('login', [AdminAuthController::class, 'showLoginView'])->name('user.login.view');
        Route::get('{id}/user/edit-permissions', [UserController::class, 'editPermissions'])->name('user.edit-permissions');
    Route::post('per/{id}/user/update-permissions', [UserController::class, 'updatePermissions'])->name('users.update-permissions');
    //


});


Route::prefix('/cms/admin/')->middleware('auth:user')->group(function () {
    Route::resource('permissions', PermissionController::class);
        Route::resource('roles', RoleController::class);

          Route::get('roles/{id}/edit-permissions', [RoleController::class, 'editRolePermissions'])->name('roles.edit-permissions');
    Route::post('roles/{id}/update-permissions', [RoleController::class, 'updateRolePermissions'])->name('roles.update-permissions');
     Route::get('{id}/user/edit-roles', [UserController::class, 'editRoles'])->name('user.edit-roles');
    Route::post('per/{id}/user/update-roles', [UserController::class, 'updateRoles'])->name('users.update-roles');

        Route::get('{id}/user/edit-roles', [UserController::class, 'editRoles'])->name('user.edit-roles');
    Route::post('per/{id}/user/update-roles', [UserController::class, 'updateRoles'])->name('users.update-roles');



});



Route::prefix('cms/admin')->namespace('Auth')->group(function () {


    Route::get('login', [AdminAuthController::class, 'showLoginView'])->name('user.login.view');
    Route::post('post/login', [AdminAuthController::class, 'login'])->name('user.login.store');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{

    public function index(){
if(Auth::user()->type=='admin'){

        $users=User::where('type','!=','admin')->get();
        return view('cms.admin.users.index',['users'=>$users]);
    }

 return view('cms.admin.blocked');
    }

    public function create(){
if(Auth::user()->type=='admin'){
        return view('cms.admin.users.create');
    }
     return view('cms.admin.blocked');
}


    public function store(UserRequest $request){
if(Auth::user()->type=='admin'){
        $user=new User();
        $user->name=$request->name;
        $user->email=$request->email;
        $user->password=Hash::make($request->get('password'));
        $user->gender=$request->get('gender');
        $user->search = Hash::make(Str::random(30));

        $user->save();

        SuccessError::Success('Create Successfuly');
        return Redirect()->back();

}

 return view('cms.admin.blocked');

    }

    public function edit($id){
        if(Auth::user()->type=='admin'){
       $user=User::where('type','!=','admin')->where('id',$id)->first();
       if($user){
 return view('cms.admin.users.edit',['user'=>$user]);
       }
        return view('cms.admin.blocked');

    }
     return view('cms.admin.blocked');
    }



    public function update(UserRequest $request,$id){

        if(Auth::user()->type=='admin'){

        // dd(45);
            $user=User::where('type','!=','admin')->where('id',$id)->first();
if($user){
        $user->name=$request->name;
        $user->email=$request->email;
        if($request->password){
        $user->password=Hash::make($request->get('password'));

        }
        $user->gender=$request->get('gender');


        $user->save();

        SuccessError::Success('Update Successfuly');
        return Redirect()->back();

    }



   }
        return view('cms.admin.blocked');

    }


    public function destroy($id){
            if(Auth::user()->type=='admin'){
      $delet=    $contactUser=User::find($id)->delete();
        if($delet){

        return response()->json(['icon' => 'success', 'title' => 'User Deleted successfully'], 200);

    }

            return response()->json(['icon' => 'error', 'title' => 'User created failed'], 400);

}
    }

       public function editPermissions(Request $request, $id)
    {
if (Auth::user()->type=='admin') {
        $user = User::find($id);
        $adminPermissions = $user->permissions()->get();
        $permissions = Permission ::where('guard_name', 'user')->get();
        return view('cms.admin.users.userPermission', [
            'user' => $user,
            'permissions' => $permissions,
            'adminPermissions' => $adminPermissions]);
    }
                return view('cms.admin.blocked');

}

    public function updatePermissions(Request $request, $id)
    {
        if (Auth::user()->type=='admin') {
        $request->request->add(['id' => $id]);
        $request->validate([
            'id' => 'required|exists:users,id',
            'permissions' => 'array',
        ]);

        $user = User::find($request->get('id'));
        $permissions = Permission::findMany($request->permissions);
        $isSynced = $user->syncPermissions($permissions);
        if ($isSynced) {
            return response()->json(['icon' => 'success', 'title' => 'User permissions update failed'], 200);
        } else {
            return response()->json(['icon' => 'Failed', 'title' => 'Admin permissions update failed'], 400);
        }
    }
    }


      public function editRoles(Request $request, $id)
    {
            if (Auth::user()->type=='admin') {
        $user = User::find($id);

        $adminRoles = $user->Roles()->get();
        $Roles = Role::where('guard_name', 'user')->get();
        return view('cms.admin.users.userRoles', [
            'user' => $user,
            'roles' => $Roles,
            'adminRoles' => $adminRoles]);
    }
                    return view('cms.admin.blocked');

}

    public function updateRoles(Request $request, $id)
    {
          if (Auth::user()->type=='admin') {
        $request->request->add(['id' => $id]);
        $request->validate([
            'id' => 'required|exists:users,id',
            'roles' => 'array',
        ]);

        $user = User::find($request->get('id'));
        $roles = Role::findMany($request->roles);
        $isSynced = $user->syncRoles($roles);
        // $isSynced=1;
        if ($isSynced) {
            return response()->json(['icon' => 'success', 'title' => 'User permissions update Successfuly'], 200);
        } else {
            return response()->json(['icon' => 'Failed', 'title' => 'Admin permissions update failed'], 400);
        }
    }
     return view('cms.admin.blocked');
    }
}

resources/views/cms/admin/users/create.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>User - Create</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}">Home</a></li>
                            <li class="breadcrumb-item active">Create User</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create User</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" action="{{route('user.store')}}">
                                @csrf

                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif

                                    @if (session()->has('message'))
                                        <div class="alert {{session()->get('status')}} alert-dismissible fade show"
                                             role="alert">
                                            <span> {{ session()->get('message') }}</span>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endif

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Full Name</label>
                                        <input name="name" value="{{old('name')}}" type="text"
                                               class="form-control" id="exampleInputEmail1"
                                               placeholder="Enter name">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Email</label>
                                        <input name="email" value="{{old('email')}}" type="email"
                                               class="form-control"
                                               id="exampleInputPassword1" placeholder="Enter email">
                                    </div>

                                         <div class="form-group">
                                             <label for="exampleInputPassword1">Password</label>

                                             <input name="password"  type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter password">


                                         </div>


                                              <div class="form-group">
                                                  <label for="exampleInputPassword1">Confirm Password</label>
                                                  <input name="confirmedpassword" type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter Confirm Password">



                                              </div>



                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Gender</label>
                                        <div class="custom-control custom-radio">
                                            <input class="custom-control-input" type="radio" id="Male"
                                                   name="gender" value="Male"
                                                   @if(old('gender') == 'Male') checked @endif>
                                            <label for="Male" class="custom-control-label">Male</label>
                                        </div>
                                        <div class="custom-control custom-radio">
                                            <input class="custom-control-input" type="radio" id="Female"
                                                   name="gender" value="Female"
                                                   @if(old('gender') == 'Female') checked @endif>
                                            <label for="Female" class="custom-control-label">Female</label>
                                        </div>
                                    </div>

                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')

@endsection

resources/views/cms/admin/users/edit.blade.php
@extends('cms.admin.parent')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>User - Update</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}">Home</a></li>
                        <li class="breadcrumb-item active">Update User</li>

                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Update User</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="{{route('user.update',$user->id)}}">
                            @method('put')
                            @csrf

                            <div class="card-body">
                                @if ($errors->any())
                                <div class="alert alert-danger" role="alert">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif

                                @if (session()->has('message'))
                                <div class="alert {{session()->get('status')}} alert-dismissible fade show" role="alert">
                                    <span> {{ session()->get('message') }}</span>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                @endif

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Full Name</label>
                                    <input name="name" value="{{$user->name}}" type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter name">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Email</label>
                                    <input name="email" value="{{$user->email}}" type="email" class="form-control" id="exampleInputPassword1" placeholder="Enter email">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputPassword1">Change Password</label>

                                    <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter password">


                                </div>
                                <input hidden value={{$user->id}} name="id">




                                <div class="form-group">
                                    <label for="exampleInputPassword1">Gender</label>
                                    <div class="custom-control custom-radio">
                                        <input class="custom-control-input" type="radio" id="Male" name="gender" value="Male" @if($user->gender=='Male' ) checked @endif>
                                        <label for="Male" class="custom-control-label">Male</label>
                                    </div>
                                    <div class="custom-control custom-radio">
                                        <input class="custom-control-input" type="radio" id="Female" name="gender" value="Female" @if($user->gender=='Female' ) checked @endif>

                                        <label for="Female" class="custom-control-label">Female</label>
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection

@section('script')

@endsection

resources/views/cms/admin/users/index.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Users</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}">Home</a></li>
                            <li class="breadcrumb-item active">Users</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Security - Users</h3>
                            <a href="{{route('user.create')}}" class="btn btn-sm btn-info float-right">Create New
                                User</a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Permission</th>

                                    <th>Roles</th>





                                    <th>Gender</th>

                                    <th>Settings</th>
                                </tr>
                                </thead>
                                <tbody>
                                <span hidden>{{$count = 0}}</span>
                                @foreach($users as $user)
                                    <tr>
                                        <td><span class="badge badge-info">{{++$count}}</span></td>
                                        <td>{{$user->id}}</td>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                                                  <td>
                                                                      <a class="btn btn-primary btn-sm" href="{{route('user.edit-permissions',[$user->id])}}">
                                                                          <i class="fas fa-sign">
                                                                          </i>
                                                                          Permission
                                                                      </a>
                                                                  </td>


                                                                  <td>
                                                                      <a class="btn btn-danger btn-sm" href="{{route('user.edit-roles',[$user->id])}}">

                                                                          <i class="fas fa-signature">
                                                                          </i>
                                                                          Roles
                                                                      </a>
                                                                  </td>


                                        <td>
                                            @if($user->gender == 'Male')
                                                <span class="badge badge-info">{{$user->gender}}</span>
                                            @else
                                                <span class="badge badge-warning">{{$user->gender}}</span>
                                            @endif
                                        </td>


                                        </td>

                                        <td>
                                            <a href="#" onclick="confirmDelete(this, '{{$user->id}}')"
                                               class="btn btn-xs btn-danger" style="color: white;">Delete</a>
                                            <a href="{{route('user.edit',[$user->id])}}"
                                               class="btn btn-xs btn-info" style="color: white;">Edit</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                            <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
  <th>Permission</th>

  <th>Roles</th>


                                    <th>Gender</th>

                                    <th>Settings</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <!-- DataTables -->
    <script src="{{asset('cms/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('cms/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>

        function confirmDelete(app, id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    deleteUser(app, id)
                }
            })
        }

        function deleteUser(app, id) {
            axios.delete('/cms/admin/user/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>
@endsection