routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\AdminAuthController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('cms.admin.parent');
})->middleware('auth:user');

Route::prefix('/cms/admin/')->middleware('auth:user')->group(function () {

    Route::resource('user', UserController::class);
    Route::resource('file', FileController::class);
    Route::get('logout', [AdminAuthController::class, 'logout'])->name('admin.logout');

    Route::get('password/reset', [AdminAuthController::class, 'showResetPasswordView'])->name('admin.password_reset_view');
    Route::post('password/reset', [AdminAuthController::class, 'resetPassword'])->name('admin.password_reset');

    Route::get('/', [AdminController::class, 'dashbord'])->name('admin.dashbord');
    Route::get('login', [AdminAuthController::class, 'showLoginView'])->name('user.login.view');
        Route::get('{id}/user/edit-permissions', [UserController::class, 'editPermissions'])->name('user.edit-permissions');
    Route::post('per/{id}/user/update-permissions', [UserController::class, 'updatePermissions'])->name('users.update-permissions');
    //


});


Route::prefix('/cms/admin/')->middleware('auth:user')->group(function () {
    Route::resource('permissions', PermissionController::class);
        Route::resource('roles', RoleController::class);

          Route::get('roles/{id}/edit-permissions', [RoleController::class, 'editRolePermissions'])->name('roles.edit-permissions');
    Route::post('roles/{id}/update-permissions', [RoleController::class, 'updateRolePermissions'])->name('roles.update-permissions');
     Route::get('{id}/user/edit-roles', [UserController::class, 'editRoles'])->name('user.edit-roles');
    Route::post('per/{id}/user/update-roles', [UserController::class, 'updateRoles'])->name('users.update-roles');

        Route::get('{id}/user/edit-roles', [UserController::class, 'editRoles'])->name('user.edit-roles');
    Route::post('per/{id}/user/update-roles', [UserController::class, 'updateRoles'])->name('users.update-roles');



});



Route::prefix('cms/admin')->namespace('Auth')->group(function () {


    Route::get('login', [AdminAuthController::class, 'showLoginView'])->name('user.login.view');
    Route::post('post/login', [AdminAuthController::class, 'login'])->name('user.login.store');
});

app/Models/File.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    use HasFactory;
}

app/Http/Controllers/FileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FileRequest;
use App\Models\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $files=File::all();
        return view('cms.admin.files.index',['files'=>$files]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
          if (ControllersService::checkPermission('create-file', 'user')

            || Auth::user()->type=='admin') {
        return view('cms.admin.files.create');
            }
             return view('cms.admin.blocked');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FileRequest $request)
    {
        if (ControllersService::checkPermission('create-file', 'user')

            || Auth::user()->type=='admin') {

        $file=new File();
        $file->title=$request->title;
        $file->content=$request->content;
        $file->save();
          SuccessError::Success('Create Successfuly');
        return Redirect()->back();

            }
             return view('cms.admin.blocked');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        if (ControllersService::checkPermission('show-file', 'user')

            || Auth::user()->type=='admin') {
        $file=File::find($id);
        return view('cms.admin.files.show',['file'=>$file]);

            }
             return view('cms.admin.blocked');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (ControllersService::checkPermission('update-file', 'user')

            || Auth::user()->type=='admin') {
        // dd(45);
        $file=File::find($id);
        return view('cms.admin.files.edit',['file'=>$file]);
        //
            }
             return view('cms.admin.blocked');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (ControllersService::checkPermission('update-file', 'user')

            || Auth::user()->type=='admin') {
        $file= File::find($id);
        $file->title=$request->title;
        $file->content=$request->content;
        $file->save();
          SuccessError::Success('Update Successfuly');
        return Redirect()->back();

            }
             return view('cms.admin.blocked');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (ControllersService::checkPermission('delete-file', 'user')

            || Auth::user()->type=='admin') {
        $delet=    $contactUser=file::find($id)->delete();
        if($delet){

        return response()->json(['icon' => 'success', 'title' => 'File Deleted successfully'], 200);

    }

            return response()->json(['icon' => 'error', 'title' => 'File created failed'], 400);
}
 return view('cms.admin.blocked');

    }
}

resources/views/cms/admin/files/create.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>File - Create</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}">Home</a></li>
                            <li class="breadcrumb-item active">Create File</li>

                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create File</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" action="{{route('file.store')}}">
                                @csrf

                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif

                                    @if (session()->has('message'))
                                    <div class="alert {{session()->get('status')}} alert-dismissible fade show" role="alert">
                                        <span> {{ session()->get('message') }}<span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                    @endif

   <div class="form-group">
       <label for="exampleInputPassword1">Title file</label>
       <input  name="title" value="{{old('title')}}" type="text" class="form-control" id="exampleInputPassword1" placeholder="Enter  Titles">
   </div>


                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Contenet</label>
                                        <textarea col="10" id="content" row="10" name="content" type="text" placeholder="Enter Content" class="textarea form-control no-resize summernote">{{old('content')}}</textarea>



                                    </div>

                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')

<script src="https://cdn.jsdelivr.net/npm/trumbowyg@2"></script>
<link href="https://cdn.jsdelivr.net/npm/trumbowyg@2/dist/ui/trumbowyg.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/vue-trumbowyg@3"></script>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://unpkg.com/vee-validate@<3.0.0"></script>

<script>

$(document).ready(function() {

$('#content').summernote({



height: 300,

});



});

</script>
@endsection

resources/views/cms/admin/files/edit.blade.php
@extends('cms.admin.parent')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>File - Create</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}">Home</a></li>
                        <li class="breadcrumb-item active">Create File</li>

                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Create File</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="{{route('file.update',$file->id)}}">
                            @csrf
                            @method('put')

                            <div class="card-body">
                                @if ($errors->any())
                                <div class="alert alert-danger" role="alert">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif

                                @if (session()->has('message'))
                                <div class="alert {{session()->get('status')}} alert-dismissible fade show" role="alert">
                                    <span> {{ session()->get('message') }}<span>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                </div>
                                @endif

                                <div class="form-group">
                                    <label for="exampleInputPassword1">Title file</label>
                                    <input name="title" value="{{$file->title}}" type="text" class="form-control" id="exampleInputPassword1" placeholder="Enter  Titles">

                                </div>


                                <div class="form-group">
                                    <label for="exampleInputPassword1">Contenet</label>
                                    <textarea col="10" id="content" row="10" name="content" type="text" placeholder="Enter Content" class="textarea form-control no-resize summernote">{{$file->content}}</textarea>




                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection

@section('script')

<script src="https://cdn.jsdelivr.net/npm/trumbowyg@2"></script>
<link href="https://cdn.jsdelivr.net/npm/trumbowyg@2/dist/ui/trumbowyg.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/vue-trumbowyg@3"></script>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://unpkg.com/vee-validate@<3.0.0"></script>

<script>
    $(document).ready(function() {

        $('#content').summernote({



            height: 300,

        });



    });

</script>
@endsection

resources/views/cms/admin/files/index.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Files</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="#" onClick="history.go(-1)">Back</a></li>




                            <li class="breadcrumb-item active">Files</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Files</h3>

                            {{-- @can('create-category') --}}
                            @if(auth()->user()->can('create-file')||Auth::user()->type=='admin')

                                <a href="{{route('file.create')}}" class="btn btn-sm btn-info float-right">Create
                                    New
                                    File</a>
                                    @endif
                            {{-- @endcan --}}
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>

                                    <th>Title</th>

                                                          @if(auth()->user()->can('update-file')||auth()->user()->can('show-file')||auth()->user()->can('delete-file') || Auth::user()->type=='admin')


                                    <th>Settings</th>
                                    @endif
                                </tr>
                                </thead>
                                <tbody>
                                <span hidden>{{$count = 0}}</span>
                                @foreach($files as $item)
                                    <tr>
                                        <td><span class="badge badge-info">{{++$count}}</span></td>


                                        <td>{{$item->title}}</td>






                                                          @if(auth()->user()->can('update-file')||auth()->user()->can('show-file')||auth()->user()->can('delete-file') || Auth::user()->type=='admin')





                                        <td>


 @if(auth()->user()->can('delete-file')||Auth::user()->type=='admin')

                                                <a href="#" onclick="confirmDelete(this, '{{$item->id}}')"

                                                   class="btn btn-xs btn-danger" style="color: white;">Delete</a>
@endif
 @if(auth()->user()->can('update-file')||Auth::user()->type=='admin')


                                                <a href="{{route('file.edit',[$item->id])}}"


                                                   class="btn btn-xs btn-info" style="color: white;">Edit</a>

@endif
 @if(auth()->user()->can('show-file')||Auth::user()->type=='admin')


                                                    <a href="{{route('file.show',[$item->id])}}" class="btn btn-xs btn-success" style="color: white;">Show</a>
@endif

                                            {{-- @endcan --}}
                                        </td>

                                        @endif

                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                       <th>#</th>

                                       <th>Title</th>

                                                          @if(auth()->user()->can('update-file')||auth()->user()->can('show-file')||auth()->user()->can('delete-file') || Auth::user()->type=='admin')


                                       <th>Settings</th>
                                       @endif

                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        {{-- <div class="row justify-content-center">
                            {{$categoriesData->render()}}
                        </div> --}}
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')


    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    deleteCategory(app, id)
                }
            })
        }

        function deleteCategory(app, id) {
            axios.delete('/cms/admin/file/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>
@endsection

resources/views/cms/admin/files/show.blade.php
@extends('cms.admin.parent')
@section('content')
  <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
          <div class="container-fluid">
              <div class="row mb-2">
                  <div class="col-sm-6">
                      <h1>{{$file->title}}</h1>

                  </div>
                  <div class="col-sm-6">
                      <ol class="breadcrumb float-sm-right">
                          <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}">Home</a></li>
                          <li class="breadcrumb-item active">{{$file->title}}</li>
                      </ol>
                  </div>
              </div>
          </div><!-- /.container-fluid -->
      </section>

      <!-- Main content -->
      <section class="content">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-12">
                      <!-- Default box -->
                      <div class="card">
                          <div class="card-header">
                              <h3 class="card-title">{{$file->title}}</h3>


                          </div>
                          <div class="card-body">
                            {!!$file->content!!}
                          </div>
                          <!-- /.card-body -->
                          <div class="card-footer">

                          </div>
                          <!-- /.card-footer-->
                      </div>
                      <!-- /.card -->
                  </div>
              </div>
          </div>
      </section>
      <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


@endsection